server:
  port: 8010
  servlet:
    session:
      timeout: 86400
spring:
  application:
    name: Yushan Backend
  transaction:
    rollback-on-commit-failure: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
      timeout: 1000
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    username: ${MAIL_USERNAME:1784304095@qq.com}
    password: ${MAIL_PASSWORD:fmgjizhjdbbabiib}
    port: ${MAIL_PORT:465}
    default-encoding: UTF-8
    protocol: smtps
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
  devtools:
    restart:
      enabled: false

mybatis:
  mapper-locations: classpath:/mapper/**Mapper.xml
  type-aliases-package: com.yushan.backend.entity
  config-location: classpath:config/mybatis-config.xml

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YushanBackendJWTSecretKey2025ForSecureTokenGenerationAndValidation}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}  # 15 minutes in milliseconds
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}  # 7 days in milliseconds
  issuer: ${JWT_ISSUER:yushan-backend}
  algorithm: ${JWT_ALGORITHM:HS256}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info