server:
  port: 8010
  servlet:
    session:
      timeout: 86400
spring:
  application:
    name: Yushan Backend
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  transaction:
    rollback-on-commit-failure: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  data:
    redis:
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      timeout: 1000

mybatis:
  mapper-locations: classpath:/mapper/**Mapper.xml
  type-aliases-package: com.yushan.backend.entity
  config-location: classpath:config/mybatis-config.xml

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YushanBackendJWTSecretKey2024ForSecureTokenGenerationAndValidation}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}  # 15 minutes in milliseconds
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}  # 7 days in milliseconds
  issuer: ${JWT_ISSUER:yushan-backend}
  algorithm: ${JWT_ALGORITHM:HS256}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: info