# GitHub Environment configuration for Production
# This file defines environment-specific settings and protection rules

name: yushan-production
displayName: Yushan Production Environment
description: Production environment for live application

# Protection rules
protection_rules:
  # Require approval for deployments (CRITICAL for production)
  required_reviewers: [] # Replace with your GitHub username
  
  # Wait timer before deployment (optional)
  wait_timer: 0  # minutes
  
  # Prevent self-review
  prevent_self_review: true
  
  # Restrict to specific branches (main and ci-cd-testing for production testing)
  deployment_branch_policy:
    protected_branches: false
    custom_branch_policies: true
    custom_branches:
      - main
      - ci-cd-testing

# Environment secrets (will be set in GitHub UI)
# These should be configured in GitHub repository settings
secrets:
  # Railway deployment
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  
  # Database (Supabase - Production)
  PRODUCTION_DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
  
  # Cache (Upstash - Production)
  PRODUCTION_REDIS_URL: ${{ secrets.PRODUCTION_REDIS_URL }}
  
  # Production URL
  PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
